export const data = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phoneNumber: "+1234567890",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phoneNumber: "+9876543210",
  },
  {
    id: 3,
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    phoneNumber: "+1122334455",
  },
  {
    id: 4,
    firstName: "Bob",
    lastName: "Williams",
    email: "bob.williams@example.com",
    phoneNumber: "+4455667788",
  },
  {
    id: 5,
    firstName: "Eva",
    lastName: "Miller",
    email: "eva.miller@example.com",
    phoneNumber: "+9988776655",
  },
  {
    id: 6,
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@example.com",
    phoneNumber: "+3322114455",
  },
  {
    id: 7,
    firstName: "Grace",
    lastName: "Anderson",
    email: "grace.anderson@example.com",
    phoneNumber: "+1122337788",
  },
  {
    id: 8,
    firstName: "Mark",
    lastName: "Taylor",
    email: "mark.taylor@example.com",
    phoneNumber: "+7788991122",
  },
  {
    id: 9,
    firstName: "Sophia",
    lastName: "Clark",
    email: "sophia.clark@example.com",
    phoneNumber: "+3344556677",
  },
  {
    id: 10,
    firstName: "William",
    lastName: "White",
    email: "william.white@example.com",
    phoneNumber: "+1122334455",
  },
  {
    id: 11,
    firstName: "Emma",
    lastName: "Turner",
    email: "emma.turner@example.com",
    phoneNumber: "+9988776655",
  },
  {
    id: 12,
    firstName: "Daniel",
    lastName: "Harris",
    email: "daniel.harris@example.com",
    phoneNumber: "+3322114455",
  },
  {
    id: 13,
    firstName: "Olivia",
    lastName: "Cooper",
    email: "olivia.cooper@example.com",
    phoneNumber: "+1122337788",
  },
  {
    id: 14,
    firstName: "James",
    lastName: "Ward",
    email: "james.ward@example.com",
    phoneNumber: "+7788991122",
  },
  {
    id: 15,
    firstName: "Ava",
    lastName: "Evans",
    email: "ava.evans@example.com",
    phoneNumber: "+3344556677",
  },
  {
    id: 16,
    firstName: "Liam",
    lastName: "Baker",
    email: "liam.baker@example.com",
    phoneNumber: "+1122334455",
  },
  {
    id: 17,
    firstName: "Mia",
    lastName: "Fisher",
    email: "mia.fisher@example.com",
    phoneNumber: "+9988776655",
  },
  {
    id: 18,
    firstName: "Noah",
    lastName: "Perez",
    email: "noah.perez@example.com",
    phoneNumber: "+3322114455",
  },
  {
    id: 19,
    firstName: "Isabella",
    lastName: "Turner",
    email: "isabella.turner@example.com",
    phoneNumber: "+1122337788",
  },
  {
    id: 20,
    firstName: "Logan",
    lastName: "Campbell",
    email: "logan.campbell@example.com",
    phoneNumber: "+7788991122",
  },
];
