export const data = [
  {
    id: 1,
    eventName: "Birthday Party",
    eventStartDate: "15-05-2024",
    eventEndDate: "15-05-2024",
    address: "123 Main St, Cityville",
    contactGroup: ["Friends", "Family"],
  },
  {
    id: 2,
    eventName: "Company Retreat",
    eventStartDate: "01-07-2024",
    eventEndDate: "03-07-2024",
    address: "Mountain Resort, Natureland",
    contactGroup: ["Work Colleagues"],
  },
  {
    id: 3,
    eventName: "Book Club Meeting",
    eventStartDate: "10-06-2024",
    eventEndDate: "10-06-2024",
    address: "Local Library, Booktown",
    contactGroup: ["Book Club"],
  },
  {
    id: 4,
    eventName: "Summer BBQ",
    eventStartDate: "20-08-2024",
    eventEndDate: "20-08-2024",
    address: "456 Oak St, Sunnyside",
    contactGroup: ["Neighbours", "Friends"],
  },
  {
    id: 5,
    eventName: "Tech Conference",
    eventStartDate: "15-09-2024",
    eventEndDate: "17-09-2024",
    address: "Tech Center, Innovation City",
    contactGroup: ["Tech Enthusiasts", "Work Colleagues"],
  },
  {
    id: 6,
    eventName: "Language Exchange Meetup",
    eventStartDate: "25-06-2024",
    eventEndDate: "25-06-2024",
    address: "Community Center, Multicity",
    contactGroup: ["Language Exchange"],
  },
  {
    id: 7,
    eventName: "Pet Playdate",
    eventStartDate: "08-07-2024",
    eventEndDate: "08-07-2024",
    address: "Dog Park, Petville",
    contactGroup: ["Pet Owners"],
  },
  {
    id: 8,
    eventName: "Outdoor Movie Night",
    eventStartDate: "05-08-2024",
    eventEndDate: "05-08-2024",
    address: "Community Park, Cinematown",
    contactGroup: ["Friends", "Neighbours"],
  },
  {
    id: 9,
    eventName: "Fitness Challenge",
    eventStartDate: "01-06-2024",
    eventEndDate: "30-06-2024",
    address: "Local Gym, Health City",
    contactGroup: ["Fitness Freaks"],
  },
  {
    id: 10,
    eventName: "Photography Workshop",
    eventStartDate: "20-07-2024",
    eventEndDate: "20-07-2024",
    address: "Art Studio, Creativeland",
    contactGroup: ["Photography Club", "Artists Circle"],
  },
  {
    id: 11,
    eventName: "Community Cleanup",
    eventStartDate: "01-09-2024",
    eventEndDate: "01-09-2024",
    address: "Citywide, Green City",
    contactGroup: ["Volunteer Team"],
  },
  {
    id: 12,
    eventName: "Coding Bootcamp",
    eventStartDate: "15-06-2024",
    eventEndDate: "30-06-2024",
    address: "Tech Institute, Codetown",
    contactGroup: ["Coding Club", "Tech Enthusiasts"],
  },
  {
    id: 13,
    eventName: "Family Reunion",
    eventStartDate: "25-07-2024",
    eventEndDate: "25-07-2024",
    address: "Grandparents' House, Familyville",
    contactGroup: ["Family"],
  },
  {
    id: 14,
    eventName: "Foodie Festival",
    eventStartDate: "10-08-2024",
    eventEndDate: "12-08-2024",
    address: "Downtown Square, Culinary City",
    contactGroup: ["Foodies"],
  },
  {
    id: 15,
    eventName: "Gaming Marathon",
    eventStartDate: "05-06-2024",
    eventEndDate: "06-06-2024",
    address: "Gaming Lounge, Gametown",
    contactGroup: ["Gaming Squad"],
  },
  {
    id: 16,
    eventName: "Music Concert",
    eventStartDate: "10-09-2024",
    eventEndDate: "10-09-2024",
    address: "Outdoor Arena, Melodytown",
    contactGroup: ["Music Lovers"],
  },
  {
    id: 17,
    eventName: "Community Garden Workshop",
    eventStartDate: "12-06-2024",
    eventEndDate: "12-06-2024",
    address: "Community Garden, Green City",
    contactGroup: ["Hobbyists", "Neighbours"],
  },
  {
    id: 18,
    eventName: "Art Exhibition Opening",
    eventStartDate: "30-07-2024",
    eventEndDate: "30-07-2024",
    address: "Art Gallery, Creativeland",
    contactGroup: ["Artists Circle"],
  },
  {
    id: 19,
    eventName: "Beach Cleanup",
    eventStartDate: "15-08-2024",
    eventEndDate: "15-08-2024",
    address: "Coastline, Seasidetown",
    contactGroup: ["Volunteer Team"],
  },
  {
    id: 20,
    eventName: "Study Group Session",
    eventStartDate: "08-06-2024",
    eventEndDate: "08-06-2024",
    address: "Library, Academia City",
    contactGroup: ["Study Group"],
  },
];
