export const data = [
  {
    id: 1,
    name: "John's Birthday Bash",
    eventType: "Birthday",
    event: "Party",
    price: 100,
    description: "A fun-filled birthday celebration for John.",
    photo: "https://example.com/birthday_photo.jpg",
  },
  {
    id: 2,
    name: "Alice's Wedding",
    eventType: "Marriage",
    event: "Wedding",
    price: 5000,
    description: "Join us in celebrating the union of Alice and Bob.",
    photo: "https://example.com/wedding_photo.jpg",
  },
  {
    id: 3,
    name: "Company Retreat",
    eventType: "Other",
    event: "Retreat",
    price: 2000,
    description: "Annual retreat for team building and relaxation.",
    photo: null, // No photo available
  },
  {
    id: 4,
    name: "Summer BBQ Party",
    eventType: "Other",
    event: "Party",
    price: 50,
    description: "Casual barbecue party to enjoy the summer vibes.",
    photo: "https://example.com/bbq_party_photo.jpg",
  },
  {
    id: 5,
    name: "Graduation Ceremony",
    eventType: "Other",
    event: "Ceremony",
    price: 200,
    description: "Celebrate the achievements of our graduates.",
    photo: "https://example.com/graduation_ceremony_photo.jpg",
  },
  {
    id: 6,
    name: "Anniversary Dinner",
    eventType: "Other",
    event: "Dinner",
    price: 150,
    description: "Romantic dinner to celebrate a special anniversary.",
    photo: "https://example.com/anniversary_dinner_photo.jpg",
  },
  {
    id: 7,
    name: "Tech Conference",
    eventType: "Conference",
    event: "Technology",
    price: 300,
    description: "Gathering of tech enthusiasts and industry experts.",
    photo: "https://example.com/tech_conference_photo.jpg",
  },
  {
    id: 8,
    name: "Art Exhibition",
    eventType: "Exhibition",
    event: "Art",
    price: 75,
    description: "Showcasing various forms of artistic expression.",
    photo: "https://example.com/art_exhibition_photo.jpg",
  },
  {
    id: 9,
    name: "Fitness Bootcamp",
    eventType: "Workshop",
    event: "Fitness",
    price: 30,
    description: "Intense fitness workshop to boost your workout routine.",
    photo: "https://example.com/fitness_bootcamp_photo.jpg",
  },
  {
    id: 10,
    name: "Film Screening",
    eventType: "Entertainment",
    event: "Film",
    price: 15,
    description: "Enjoy a screening of classic and indie films.",
    photo: "https://example.com/film_screening_photo.jpg",
  },
  {
    id: 11,
    name: "Book Club Meeting",
    eventType: "Meeting",
    event: "Literature",
    price: 0,
    description: "Discussing the latest books and literary works.",
    photo: null,
  },
  {
    id: 12,
    name: "Science Fair",
    eventType: "Fair",
    event: "Science",
    price: 0,
    description: "Showcasing innovative projects and experiments.",
    photo: "https://example.com/science_fair_photo.jpg",
  },
  {
    id: 13,
    name: "Music Festival",
    eventType: "Festival",
    event: "Music",
    price: 75,
    description: "Live performances and music from various genres.",
    photo: "https://example.com/music_festival_photo.jpg",
  },
  {
    id: 14,
    name: "Food Tasting Event",
    eventType: "Tasting",
    event: "Food",
    price: 20,
    description: "Explore a variety of delicious food and beverages.",
    photo: "https://example.com/food_tasting_event_photo.jpg",
  },
  {
    id: 15,
    name: "Charity Run",
    eventType: "Sports",
    event: "Run",
    price: 10,
    description: "Run for a cause and support charitable organizations.",
    photo: "https://example.com/charity_run_photo.jpg",
  },
  {
    id: 16,
    name: "Comedy Show",
    eventType: "Entertainment",
    event: "Comedy",
    price: 25,
    description: "Laughs and entertainment with stand-up comedians.",
    photo: "https://example.com/comedy_show_photo.jpg",
  },
  {
    id: 17,
    name: "Gardening Workshop",
    eventType: "Workshop",
    event: "Gardening",
    price: 15,
    description: "Learn the art and science of gardening.",
    photo: "https://example.com/gardening_workshop_photo.jpg",
  },
  {
    id: 18,
    name: "Virtual Reality Demo",
    eventType: "Demo",
    event: "Technology",
    price: 10,
    description: "Experience the latest in virtual reality technology.",
    photo: "https://example.com/vr_demo_photo.jpg",
  },
  {
    id: 19,
    name: "Fashion Show",
    eventType: "Show",
    event: "Fashion",
    price: 30,
    description: "Showcasing the latest trends in fashion and design.",
    photo: "https://example.com/fashion_show_photo.jpg",
  },
  {
    id: 20,
    name: "Cooking Class",
    eventType: "Class",
    event: "Cooking",
    price: 25,
    description: "Hands-on cooking class with expert chefs.",
    photo: "https://example.com/cooking_class_photo.jpg",
  },
];
